logging.level.org.springframework=debug
#spring.h2.console.enabled=true
#spring.datasource.url = jdbc:h2:mem:testdb

server.port = 5000

spring.jpa.defer-datasource-initialization = true
spring.jpa.show-sql=true



#spring.datasource.url=jdbc:mysql://localhost:3306/sportsappdatabase

#spring.datasource.username=root
#spring.datasource.password=12345678

spring.datasource.url=jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:sportsappdatabase}
spring.datasource.username=${RDS_USERNAME:root}
spring.datasource.password=${RDS_PASSWORD:12345678}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# \connect root@localhost:3306
#spring.security.user.name=test
#spring.security.user.password=test


